services:
  - type: web
    name: quickslot-be
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_PATH
        value: /data/quickslot.db
    disk:
      name: quickslot-db
      mountPath: /data
      sizeGB: 1
